### ISSUE TITLE
Weird Issue with Connected Textures

### ISSUE THREAD

**Issue by MastaC729** [Chisel-2/Chisel-2#293] opened 2015-04-13 03:34 UTC
My friend was placing Hex plating when he noticed that a chunk of his base was doing the following:

http://puu.sh/hbVJX/3831ede03a.png

I have no idea how to reproduce the issue. Hope the image helps.

**Comment by tterrag1098** [comment] 2015-04-13 03:57
Where that issue begins, what is the coordinate difference? Is it a chunk boundary?

For instance, if that line is x=0 or z=0 we may have an off-by-one error on our hands.

**Comment by Drullkus** [comment] 2015-04-13 06:10
What the hell?

I'll look at this.

**Comment by tterrag1098** [comment] 2015-04-13 12:04
What's weird is they don't seem to just be the wrong textures, it looks like the textures are just...completely *off*. Not aligned at all, off by amounts smaller than a full block. This is very strange indeed.

Do you have optifine installed, perchance?

**Comment by Drullkus** [comment] 2015-04-13 22:52
This is the large hexplating texture, tterrag, not the smaller one.

**Comment by tterrag1098** [comment] 2015-04-13 22:54
I know that. My observation still stands

**Comment by CptSpaceToaster** [comment] 2015-04-13 23:09
It takes deep magic to turn textures by 90 degrees.... This does not bode well.

**Comment by tterrag1098** [comment] 2015-04-14 01:57
No it doesn't lol. There are fields in RenderBlocks for that.

**Comment by Drullkus** [comment] 2015-04-14 03:52
Oh lord... You're right, they ARE rotated. Welp, I'm out of my depth here :(

**Comment by MastaC729** [comment] 2015-04-17 01:26
The coords of it are: x = -64, z = 1247 to x = -79, z = 1232

So yes it is one single chunk. We do not have OptiFine installed. If you need any other mods that may affect the rendering code, we also have FastCraft installed.

**Comment by warlordjones** [comment] 2015-05-28 19:13
Cannot reproduce...closing for now.

**Closed by warlordjones** 2015-05-28 19:13 UTC
Labels: bug
