### ISSUE TITLE
Massive Fans

### ISSUE THREAD

**Issue by primetoxinz** [Chisel-2/Chisel-2#365] opened 2015-07-08 01:19 UTC
is there any possibility of getting the massive fans to be off the grid? they are great but I want to be able to separate them a little...

**Comment by WesCook** [comment] 2015-07-31 13:15
Would also love a fix for this.  To say the least, my wind tunnel did not go as expected.

![2015-07-31_06 14 03](https://cloud.githubusercontent.com/assets/792101/9007978/74137058-374b-11e5-9f01-e5b9166b9629.png)

**Comment by CptSpaceToaster** [comment] 2015-07-31 14:10
First... you put a 3x3 square in a 4x4 hole... I don't we can help you at ALL with that one.

The simplest thing is build your base on grid... This is a toss-up between CPU time and looks. Moving to a tile-entity or more "world-aware" block could _maybe_ fix some of this, but that's bound to eat up a non-trivial amount CPU time if you use a lot of fans.

**Comment by WesCook** [comment] 2015-07-31 14:15
"First... you put a 3x3 square in a 4x4 hole..."

Ah, figured somebody would comment on that.  Was just showing how the grid worked out though.  Was going to do 3x3.  :)

I don't claim to know a lot about these matters, but can't you set up a non-ticking tile entity that only affects GPU rendering, but doesn't require CPU processing?  Other then on block updates to recalculate the grid, that is.

Or the less-precise solution is just to make it 9 segments.  "Massive Fan Top Left", and so on.  A bit uglier a solution, I know, but solves performance issues.  Would syncing textures be an issue?  Just spitballing ideas.

**Comment by CptSpaceToaster** [comment] 2015-07-31 14:28
> Other then on block updates to recalculate the grid, that is.
This requires that we take a block ID, and add metadata to it, and handle the grid calculation.  That isn't "simple" and requires that we turn Fans into Ticking Tile-Entities.  So in short... there's no way to implement that suggestion without hitting CPU time.

> Or the less-precise solution is just to make it 9 segments.
How would players handle this in survival?

**Comment by TheCricket** [comment] 2015-07-31 15:37
The Massive Fan can't be "off the grid" because then it wouldn't have power

**Comment by CptSpaceToaster** [comment] 2015-07-31 15:50
Yeah... I'm not a fan.

**Comment by WesCook** [comment] 2015-07-31 15:57
While I respect your decision, I also think it blows.

**Comment by TheCricket** [comment] 2015-07-31 15:59
the fan puns...

**Comment by Drullkus** [comment] 2015-07-31 18:25
I'm a fan of this discussion, I think it's pretty cool. These puns are really blowing me away!

**Comment by Xemiru** [comment] 2015-09-24 09:04
@CptSpaceToaster -initial disclaimer of being a noob that only knows how to write server plugins and not game mods-

Considering the texture's able to define itself based on an arbitrary grid map, is it possible for it to determine its texture based off of adjacent blocks? It could try and choose its texture based on whether or not its surrounded by a certain amount of blocks on select sides, e.g. if its surrounded by similar blocks on all four sides then it'd declare itself as the center piece. Though this'd only work for 3x3's and 2x2's, I guess, in which case it could try and determine based on the number of similar blocks in a given direction.

If not, lolitried.

**Comment by tterrag1098** [comment] 2015-09-24 09:15
The problem is exactly what you said, for anything but exact formations of the size, it fails. Also, the logic would be immense and require recalculating all the time. I came up with a better solution for Chisel 3.0:

http://gfycat.com/ReadyOccasionalBasilisk

**Comment by WesCook** [comment] 2015-09-24 09:17
If the texture were more dynamic that seems like a good approach.  But that'd require the texture to be tileable with specific edge pieces, and currently it's only designed for 3x3.

Though one of the Chisel forks implemented a separate solution to make it work.
https://www.reddit.com/r/feedthebeast/comments/3ilahq/coming_soon_in_chisel_30/

**Comment by tterrag1098** [comment] 2015-09-24 09:20
2 minutes too late, lol

**Comment by Xemiru** [comment] 2015-09-24 09:25
With the way it works right now, I'm getting the impression that that tool shifts the **entire** gridmap; as in every other block that works that way is affected as well. Better than constant recalc, though.

**Comment by tterrag1098** [comment] 2015-09-24 09:43
It affects the entire chunk, not the world.

**Comment by Xemiru** [comment] 2015-09-24 09:48
oh okay; didn't know the map was chunk based

**Comment by Drullkus** [comment] 2015-09-24 23:47
Completed product available in [the other chisel fork](https://github.com/Chisel-Team/Chisel).

[What it looks like (Texture and Shader): http://gfycat.com/JealousQuickArgusfish](http://gfycat.com/JealousQuickArgusfish)
1. The textures are shifted per-grid.
2. I'm not redesigning varying texture sizes of the fans....

**Closed** 2016-10-18 19:56 UTC
Labels: enhancement
