### ISSUE TITLE
Crash after inserting glass into diamond chisel

### ISSUE THREAD

**Issue by TygreWolf** [Chisel-2/Chisel-2#396] opened 2015-08-22 13:49 UTC
Inserted glass into diamond chisel causes game crash.  Chisel2 version 2.5.0.42.

java.lang.ClassCastException: com.cricketcraft.chisel.block.BlockCarvableGlass cannot be cast to com.cricketcraft.chisel.block.BlockCarvable
	at com.cricketcraft.chisel.client.gui.GuiChisel.func_73876_c(GuiChisel.java:82)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Lordmau5** [comment] 2015-08-22 19:48
Can confirm, same thing happened to me on an Obsidian Chisel just now.
http://pastebin.com/xjrfFYL7

**Comment by Optimoos** [comment] 2015-08-22 22:10
Just to complete the trifecta, it is happening with an iron chisel as well.

http://pastebin.com/e0CXzemW

**Comment by TheCricket** [comment] 2015-08-23 01:15
duplicate of #395

**Closed by TheCricket** 2015-08-23 01:15 UTC
