### ISSUE TITLE
Issue with voidstone textures

### ISSUE THREAD

**Issue by ViperZer0** [Chisel-2/Chisel-2#391] opened 2015-08-15 07:23 UTC
Most voidstone textures do not appear in the world as they do in the inventory. Instead, when placed, they simply show the texture for the raw voidstone. The affected textures are (as far as I tested):
-Runic Voidstone
-Energized Voidstone:
-Eye Voidstone

EDIT: After playing around a bit, the textures are suddenly appearing. I do not know if the problem was with my computer or not, or if this is just an issue for me, but the problem seems to have resolved itself.

**Comment by ViperZer0** [comment] 2015-08-15 07:24
EDIT 2: Some of the textures are still messed up. Actually, they are not the textures for raw voidstone, but something else entirely. Are these placeholders for future textures, perhaps?

**Comment by TheCricket** [comment] 2015-08-15 15:57
duplicate of #360

**Closed by TheCricket** 2015-08-15 15:57 UTC
