### ISSUE TITLE
Crash client.

### ISSUE THREAD

**Issue by Pilad** [Chisel-2/Chisel-2#348] opened 2015-06-27 16:30 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 27.06.15 22:28
Description: Initializing game

java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Triple
	at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:193)
	at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:457)
	at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:202)
	at com.cricketcraft.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:72)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:316)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:56)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Triple
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:193)
	at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:457)
	at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:202)
	at com.cricketcraft.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:72)
	at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:316)
	at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:56)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 168624056 bytes (160 MB) / 440459264 bytes (420 MB) up to 1583808512 bytes (1510 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1536M -XX:MaxMetaspaceSize=256M -Xincgc -XX:ParallelGCThreads=2 -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1388 63 mods loaded, 63 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.114.1388} [Forge Mod Loader] (forge-1.7.10-10.13.3.1388-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.3.1388} [Minecraft Forge] (forge-1.7.10-10.13.3.1388-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.5.111} [Not Enough Items] (10_NotEnoughItems-1.7.10-1.0.5.111-universal.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.19} [ChickenChunks] (10_ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized
	EnderStorage{1.4.7.36} [EnderStorage] (10_EnderStorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed->Pre-initialized
	Translocator{1.1.2.15} [Translocator] (10_Translocator-1.7.10-1.1.2.15-universal.jar) Unloaded->Constructed->Pre-initialized
	ttCore{MC1.7.10-0.1.1-78} [ttCore] (10_ttCore-MC1.7.10-0.1.1-78.jar) Unloaded->Constructed->Pre-initialized
	Waila{1.5.10} [Waila] (10_Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized
	wailaplugins{MC1.7.10-0.0.1-15} [WAILA Plugins] (10_WAILAPlugins-MC1.7.10-0.0.1-15.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (10_WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (10_WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (10_WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (1_CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (1_ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (1_ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.4.3A} [Big Reactors] (1_BigReactors-0.4.3A.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (4_Mantle-1.7.10-0.3.2(1).jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (4_TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (1_MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (1_RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized
	RArm{1.7.10-1.2.0-35} [Redstone Armory] (1_RedstoneArmory-1.7.10-1.2.0-35(1).jar) Unloaded->Constructed->Pre-initialized
	simplyjetpacks{1.5.1} [Simply Jetpacks] (1_SimplyJetpacks-MC1.7.10-1.5.1.jar) Unloaded->Constructed->Pre-initialized
	rfdrills{1.6} [RFDrills] (1_RFDrills-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized
	rfwindmill{0.7a} [RF Windmill] (1_rfwindmill-1.7.10-0.7a.jar) Unloaded->Constructed->Pre-initialized
	SolarExpansion{1.6a} [Solar Expansion] (1_SolarExpansion-Basic-1.6a(1).jar) Unloaded->Constructed->Pre-initialized
	SolarFlux{1.7.10-0.8a} [Solar Flux] (1_SolarFlux-1.7.10-0.8a(1).jar) Unloaded->Constructed->Pre-initialized
	SuperMultiDrills{1.7.10-1.1.0b} [Super Multi-Drills] (1_SuperMultiDrills-1.7.10-1.1.0b-16.jar) Unloaded->Constructed->Pre-initialized
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (1_ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized
	Natura{2.2.0} [Natura] (4_natura-1.7.10-2.2.0.1(1).jar) Unloaded->Constructed->Pre-initialized
	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) Unloaded->Constructed->Pre-initialized
	ExtraTiC{1.4.5} [ExtraTiC] (4_ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized
	SilentGems{@VERSION@} [Silent's Gems] (4_SilentGems-1.7.10-1.2.07b-84.jar) Unloaded->Constructed->Pre-initialized
	TiCTooltips{1.2.4} [TiC Tooltips] (4_TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized
	tinker_io{beta 1.2.1} [Tinker I/O] (4_tinker_io-1.7.10-beta1.2.1.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{0.2.14.100} [Tinkers' Mechworks] (4_TMechworks-1.7.10-0.2.14.100.jar) Unloaded->Constructed->Pre-initialized
	betterloadingscreen{1.3.2} [Better Loading Screen] ([1.7.10] BetterLoadingScreen-1.3.2.jar) Unloaded->Constructed->Pre-initialized
	chisel{2.4.0.38} [Chisel 2] (Chisel2-2.4.0.38.jar) Unloaded->Constructed->Pre-initialized
	ctmlib{1.0.0.3} [CTMLib] (Chisel2-2.4.0.38.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed->Pre-initialized
	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (4_IguanaTinkerTweaks-1.7.10-2.1.5.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) Unloaded->Constructed->Pre-initialized
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Launched Version: 1.7.10-Forge10.13.3.1388-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 9600 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TehNut** [comment] 2015-06-27 17:36
Dupe of #346?

**Comment by alexbegt** [comment] 2015-06-27 17:44
It seems so, but the crash locations in the minecraft code are different from #346.

**Comment by TheCricket** [comment] 2015-06-28 00:18
Its libraries being downloaded wrong
runs fine for everyone else

**Closed by TheCricket** 2015-06-28 00:18 UTC

**Comment by Pilad** [comment] 2015-06-28 03:46
Clear client. Vanilla lic. launcher. Forge 1388. Libraries ?

**Comment by tterrag1098** [comment] 2015-06-28 04:01
@Pilad Try updating forge, you are quite behind

**Comment by TheUnlocked** [comment] 2015-07-05 16:27
I updated my forge (which with the curse client required copying the instance folder into a backup, deleting the instance, recreating the instance with the new forge version, and putting the mods, configs, saves, etc. into the new instance folder, if anyone couldn't figure it out) and chisel 2 works perfectly now! Thanks for the fix!

**Comment by Zsashas** [comment] 2015-08-01 04:36
What did you update Forge to? Which version? I can't get the right one, it seems.

**Comment by tterrag1098** [comment] 2015-08-01 05:21
This seems to have been a problem with 1388 specifically, it was reported twice and both crashes had that version of forge. It was taken down from the forge maven so I am fairly sure it was broken. Recommended forge version should work fine.

**Comment by Zsashas** [comment] 2015-08-01 05:29
Recommended as in 1448? Well that's unfortunate...
https://github.com/MinecraftForge/MinecraftForge/issues/2059

**Comment by tterrag1098** [comment] 2015-08-01 06:24
It's no longer our problem, nothing we can do to help you at this point.

**Comment by Zsashas** [comment] 2015-08-01 06:52
Is there a way to manually download the libraries needed? Since it seems the problem is the mod isn't doing it automatically.

**Comment by tterrag1098** [comment] 2015-08-01 07:08
The libraries are included with forge. Or, should be, as it were.
